"""
Pydantic schemas and LangGraph state definitions for the ASL translation workflow.
"""

from typing import TypedDict, List
from pydantic import BaseModel, Field


class DescriptionSchema(BaseModel):
    word: str = Field(description="The English word or gloss being described.")
    hand_shape: str = Field(
        description="Description of the hand shape (e.g., 'Open 5', 'A')."
    )
    location: str = Field(description="The body location where the sign is performed.")
    movement: str = Field(description="Detailed description of the sign's movement.")
    non_manual_markers: str = Field(
        description="Facial expressions or body posture required."
    )
    is_fingerspelled: bool = Field(
        default=False,
        description="True if this word is a proper noun or abbreviation that should be fingerspelled letter by letter.",
    )
    fingerspell_letters: List[str] = Field(
        default_factory=list,
        description="Ordered list of uppercase letters to fingerspell, e.g. ['S','H','R','A','V','A','N'] for the name SHRAVAN. Only populated when is_fingerspelled is true.",
    )
    kb_verified: bool = Field(
        default=False,
        description="True if this sign's description is grounded in the verified Lifeprint/ASLU knowledge base rather than generated by the LLM.",
    )


class SentenceDescriptionSchema(BaseModel):
    signs: List[DescriptionSchema] = Field(
        description="Ordered list of signs to convey the sentence."
    )
    note: str = Field(
        description="A helpful note about ASL grammar, facial expressions, or performance tips specific to this phrase."
    )


class GrammarPlanSchema(BaseModel):
    """Schema for the Grammar Agent's planning output."""

    should_reorder: bool = Field(
        description="True if the English sentence should be reordered to fit the ASL TTC (Time-Topic-Comment) structure, False otherwise."
    )
    asl_gloss_order: str = Field(
        description="The proposed sequence of ASL glosses (words, capitalized and space-separated) following the ASL grammar structure, or the original order if no reordering is needed."
    )


class ASLState(TypedDict):
    """Represents the state flowing through the LangGraph workflow."""

    english_input: str
    translated_input: str
    final_output: SentenceDescriptionSchema
    grammar_plan: GrammarPlanSchema
    error: str
